# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3baa789976b17e5eef11195052ce475542fef5d6ec940bcdd33d717f499bece60eb38b75629bcb0ddfa1b33db5f46449312a42adb6dba23f06e905dc6a625a1e

test:
  secret_key_base: 8e43e2431301c7b26e7a51f06f3d1a61be7d75a02f32891adb31aaf9840bdb18911848bca2eeea1abe410db4f2d6605af2f3933fa53a6cc407d14a03ece49e90

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
